### ISSUE TITLE
syncDoc changed?

### ISSUE THREAD

**Issue by kjetilhp** [dappsnation/akita-ng-fire#1]
Can't find any documentation regarding the issue but it seems like syncDoc now returns the docs id instead of the actual document as before, is this intended? and what are the correct way to get the document now? service.syncActive(id) and then query.getActive()?

**Comment by GrandSchtroumpf** [comment]
Hello,
Akita-ng-fire follow the guideline of Akita for the [flow of data](https://netbasal.gitbook.io/akita/). With this in mind, data should always come from the query, and service is only here to connect with backend :
```typescript
service.syncDoc({ id });
query.selectEntity(id); // or query.getEntity(id) if you want a snapshot
```
Or 
```typescript
service.syncActive({ id });
query.selectActive();  // or query.getActove() if you want a snapshot
```

But I think it make sense that `syncActive` and `syncDoc` return the document. I'll try to update that. Thanks for the feedback.

**Comment by GrandSchtroumpf** [comment]
fix with https://github.com/dappsnation/akita-ng-fire/commit/08cf0d18c85d537bb38db546a4cfafe26c939aa7
