### ISSUE TITLE
Removed/deleted properties in Firestore are not removed/deleted from the store

### ISSUE THREAD

**Issue by stepanic** [dappsnation/akita-ng-fire#101]
`Add` and `update` properties in a specific Firestore document works perfectly but when I `remove` property from the Firestore document with (Firebase console browser) it stays in the store, which is Akita BUG.

`Add` and `remove` the whole document from the collection also works perfectly as expected.

How to reproduce the bug:
1. load data in the component with the `this.data$ = this.query.selectAll()`
2. show them in the component with `data$ | async | json`
3. OPTIONAL `add` or `update` some property this should work perfectly
4. OPTIONAL `add` or `remove` some documents from the collection this should also work perfectly
5. `remove/delete` some property from some Firestore Document from Firebase Console, in Firestore browser property are removed but not from Angular app from the Akita store
6. after the Angular app `refresh/reload` Akita store is updated with the fresh data from the Firestore and deleted property/properties from the step 5. are not visible

Lib's versions in the app:
```
"dependencies": {
    "@angular/core": "~9.1.7",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/material": "^9.2.3",
    "@angular/platform-browser": "~9.1.7",
    "@angular/platform-browser-dynamic": "~9.1.7",
    "@angular/router": "~9.1.7",
    "@datorama/akita": "^4.23.2",
    "@ngneat/until-destroy": "^7.1.6",
    "akita-ng-fire": "^1.5.13",
    "firebase": "^7.8.0",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3"
  }
```

**Comment by stepanic** [comment]
This is the demo, please check when I delete property `name` from the Firestore document it doesn't delete in the Angular app powered by Akita `Query` and `SubcollectionService`.

But when I refresh/reload page property disappears.

![omOhhZD6AG](https://user-images.githubusercontent.com/315282/82565705-27d87000-9b7b-11ea-83c6-01d780556822.gif)

https://recordit.co/omOhhZD6AG

**Comment by GrandSchtroumpf** [comment]
Hello,
Thanks for the report. We'll investigate that. Unfortunately we won't be able to look at this before next week. I hope it's not urgent on your side.

**Comment by stepanic** [comment]
@GrandSchtroumpf it's not urgent, thank you.

In the meantime, I have upgraded manually to `v2.0.3` when I saw it is available as `latest` NPM version but the same issue still exists as previously reported on the version `v1.5.13`.

**Comment by fritzschoff** [comment]
![image (1)](https://user-images.githubusercontent.com/39312833/86132363-12922200-bae7-11ea-8c46-26fbda42ec6f.png)
The new state and the old state are getting merged, that is why, you won't get an update if you delete something, you explicit need to specify the keys you want to delete. But we did a workaround for v3.
