### ISSUE TITLE
upgrade akita-ng-fire to akita v5

### ISSUE THREAD

**Issue by timothyalcaide** [dappsnation/akita-ng-fire#111]
When i would like to use akita-ng-fire with akita 5.0.0 i have an error 
`
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 39:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 47:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 55:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 64:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 69:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 77:30-42
"export 'StoreActions' was not found in '@datorama/akita'
`
@NetanelBasal told me to post an issue

**Comment by psoladoye-dev** [comment]
Any update on this issue?

**Comment by fritzschoff** [comment]
I will have a look into it.

**Comment by fritzschoff** [comment]
upgraded the lib to use akita v5. Let me know if that fixed the bug.

**Comment by fritzschoff** [comment]
have to reopen, since I found an import bug in akita v5.1.0. Going to fix it asap

**Comment by fritzschoff** [comment]
fixed with release v3
