### ISSUE TITLE
fix unit test

### ISSUE THREAD

**Issue by fritzschoff** [dappsnation/akita-ng-fire#117]
its failing cause angular/fire dropped the firesettingstoken

**Comment by saifxx** [comment]
Can you please fix this issue?. I want to start my new product using akita-ng-fire.

**Comment by fritzschoff** [comment]
what is blocking you? The library is still working, it is just the test are not running in the ci

**Comment by saifxx** [comment]
![image](https://user-images.githubusercontent.com/29164221/86904933-cec49b80-c12a-11ea-92c1-8fe8a5569c4d.png)
Nothing is showing

**Comment by saifxx** [comment]
Can you please provide a sample project with latest version of akita, firebase and akita-ng-fire?

**Comment by fritzschoff** [comment]
which version of akita are you using? You can check here in the repo the example app. This has the latest versions

**Comment by saifxx** [comment]
I have created the sample project at stackblitz: https://stackblitz.com/edit/angular-fvaf5r
And getting the same error here too: "Error: Cannot read property 'ignoreUndefinedProperties' of undefined".

**Comment by fritzschoff** [comment]
I'm using my firebase settings here, for debugging reasons and it is working
https://stackblitz.com/edit/angular-tugkkc?file=src%2Fapp%2Fapp.component.ts
maybe there is something wrong with your firebase settings?

**Comment by saifurrehmanx** [comment]
Ok I got the issue. 
It's happened when I try to add reference field in document.
![image](https://user-images.githubusercontent.com/29164221/86936284-3b558f80-c157-11ea-9657-9a4c30c319ea.png)

My firebase settings was OK.

Updated Sample: https://stackblitz.com/edit/angular-fvaf5r

Please check and let me know. :)

**Comment by fritzschoff** [comment]
ah okay, you are working with references. I created an issue for that for better tracking #126
