### ISSUE TITLE
CombineLatest doesn't emit when array is empty

### ISSUE THREAD

**Issue by GrandSchtroumpf** [dappsnation/akita-ng-fire#120]
We should use `array.length ? combineLatest(...) : of([])` when using combineLatest because it never emits if the array is empty.
This happens here for example : 
https://github.com/dappsnation/akita-ng-fire/blob/v3.0.0/projects/akita-ng-fire/src/lib/collection/collection.service.ts#L482

**Comment by fritzschoff** [comment]
fixed
