### ISSUE TITLE
Incorrect store update after entity update 

### ISSUE THREAD

**Issue by TimVanMourik** [dappsnation/akita-ng-fire#135]
**Type**
Bug

**Description**
I was playing around with your library and noticed that an after updating an entity, the new entity data appeared at the root level of my store instead of within the entity. 

**Steps to reproduce**
* Subscribe to a (sub)collection
* Update an entity in the Firestore manually by for example adding a field `foo: "bar"` or by programmatically by `this.movieService.update({ id: 1, foo: "bar" })`
* The movie store will update incorrectly:
_Actual store update (diff)_
`movies --> { id: 1, foo: "bar" }`
_Desired store update (diff)_
`movies --> entities --> 1 --> { id: 1, foo: "bar" }`

**Reason**
The store is updated with an incorrect update function (missing id) in line 44: 
https://github.com/dappsnation/akita-ng-fire/blob/b9062a8c9a4b62e8d6d1ae6355255164177cea17/projects/akita-ng-fire/src/lib/utils/sync-from-action.ts#L36-L46
The update function is missing the entity id.

**Solution**
Per the [Akita documentation](https://datorama.github.io/akita/docs/additional/events):
`runEntityStoreAction(BooksStore, EntityStoreAction.UpdateEntities, update => update(2, { title: 'New title' }));`
So this should do the trick:
`update => update(data)` should become `update => update(entityIds, data)`

**Fix**
Pass on entity id to update function, see PR #134

**Comment by fritzschoff** [comment]
thank you very much for reporting! merged with pr #134

**Comment by TimVanMourik** [comment]
Thanks for merging so quickly! 😎 Just wondering, is this auto-published to npm?

**Comment by fritzschoff** [comment]
nope but I will do now

**Comment by fritzschoff** [comment]
@TimVanMourik your fix is now available at 3.0.3

**Comment by TimVanMourik** [comment]
Thanks! I'll test ASAP 🎉

**Comment by TimVanMourik** [comment]
Tested and working 🥇
