### ISSUE TITLE
`callFunction` is not part of the Public API

### ISSUE THREAD

**Issue by wSedlacek** [dappsnation/akita-ng-fire#139]
https://github.com/dappsnation/akita-ng-fire/blob/3c9ac16fe974348239e33c452ea3f5780811979d/projects/akita-ng-fire/src/public-api.ts#L14-L26

`utils/callFunction` is not exported from the public API thus making it unaccessible.
The documentation for Calling functions also doesn't have this import in the code example.

**Comment by fritzschoff** [comment]
Thank you for reporting, going to fix it asap!

**Comment by fritzschoff** [comment]
fix is available in 3.0.4

**Comment by wSedlacek** [comment]
Thank you!
