### ISSUE TITLE
Email/Password sign-up bug

### ISSUE THREAD

**Issue by hakimio** [dappsnation/akita-ng-fire#151]
Steps to reproduce:
- Register new profile using email/password authentication
- Send email verification
- Verify email
- Try to sign-in (all the steps up to here should be done without reloading the app)

Result: After signing-in, the authentication state has the following data:
```
emailVerified: false
loading: false
profile: undefined
roles: null
uid: "foo-bar"
```

Expected result: the state should be updated correctly with correct value for `emailVerified` and `profile`.
I imagine this happens because after email verification `cred.additionalUserInfo.isNewUser` is set to `false`.

**Comment by fritzschoff** [comment]
Thanks for reporting, looking into it! 
And yes you are right. isNewUser is only set to true when you "register" so to say.

**Comment by hakimio** [comment]
@fritzschoff Just tested v3.1.2. Now when trying to sign-in, I get "Can not read property 'ref' of undefined" error:
![Stack trace](https://user-images.githubusercontent.com/768105/93305488-decdbb00-f7fe-11ea-94e1-69153ee5af6d.PNG)
![ref of undefined](https://user-images.githubusercontent.com/768105/93305512-e55c3280-f7fe-11ea-9530-75eacf64bc46.PNG)
![ref of undefined 2](https://user-images.githubusercontent.com/768105/93305526-e8efb980-f7fe-11ea-8d75-729ab3194d12.PNG)

Issue with scopes?

**Comment by fritzschoff** [comment]
Let me check

**Comment by fritzschoff** [comment]
if I console log this.collection, ref is defined... I'm trying different syntax

**Comment by fritzschoff** [comment]
new version is out. 3.1.3
