### ISSUE TITLE
Add contribution workflow

### ISSUE THREAD

**Issue by loicmarie** [dappsnation/akita-ng-fire#16]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
We can develop on `akita-ng-fire` within the `akita-ng-fire` parent app, that is the lib demo too, by: 
- cloning the repo into workspace
- `cd akita-ng-fire`
- `ng build akita-ng-fire`
- `npm link dist/akita-ng-fire`

Works well. But we can't use it in an external application, by: 
- cloning the repo into workspace
- `cd akita-ng-fire`
- `ng build akita-ng-fire`
- `cd ../my-app`
- `npm link ../dist/akita-ng-fire`

... results in broking the DI (see [angular/angular-cli#10751](https://github.com/angular/angular-cli/issues/10751))

## Expected behavior
- A dev workflow for contributing (using Nx workspaces or other)
- A `CONTRIBUTING.md` describing how to use this workflow, with an external angular app, or a playground app.

**Comment by fritzschoff** [comment]
We are happy if you want to create one, but for this small lib, there is no need for it atm
