### ISSUE TITLE
'StoreActions' was not found in '@datorama/akita'

### ISSUE THREAD

**Issue by mattbodman** [dappsnation/akita-ng-fire#161]
`ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 62:30-42
"export 'StoreActions' was not found in '@datorama/akita'
`

`@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/fire                   6.0.3
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
`

**Comment by fritzschoff** [comment]
what is your akita version?

**Comment by mattbodman** [comment]
Sorry, I should have included that.  It's 4.23.2

**Comment by mattbodman** [comment]
Sorry I should have included that.  It's 4.23.2

**Comment by fritzschoff** [comment]
No problem. There is peer dependency :
``` 
  "peerDependencies": {
    "@angular/common": ">=6.0.0 <11",
    "@angular/core": ">=6.0.0 <11",
    "@angular/router": ">=6.0.0 <11",
    "@angular/fire": ">=6.0.0",
    "@datorama/akita": ">= 5.1.1",
``` 
Not sure why you didn't get a error. Try to update to version 5 your akita version. There was a breaking change from version 4 to 5
