### ISSUE TITLE
RealTimeConfig not exported by akita-ng-fire

### ISSUE THREAD

**Issue by Disane87** [dappsnation/akita-ng-fire#175]
I guys, I want to use your RealTimeService in my application and followed the guide to start woth angular, akita and firebase. Everything is working fine. But if I want to enable the `RealtimeService` the `RealTimeConfig` mentioned here (https://github.com/dappsnation/akita-ng-fire/blob/v4.0.0/doc/real-time-db/real-time-db.md) is not found:

![image](https://user-images.githubusercontent.com/956158/103515204-98b06c00-4e6e-11eb-901a-41ee18b3e91f.png)

Is this guide deprecated?

**Comment by fritzschoff** [comment]
Hey, sorry, my mistake. Forgot to export the config. Now available in 4.1.1. Thanks for reporting!
Also if you missing any feature, please let me know!

**Comment by Disane87** [comment]
Thank you! Stay healthy 🍀
