### ISSUE TITLE
Bundle always include realtime database.

### ISSUE THREAD

**Issue by rlagkrdy** [dappsnation/akita-ng-fire#179]
Hi. 

I'm only use firestore in my project. 
But, after include reatime database, Bundle always include realtime database.
55kb increase based on gzip. 
So I lowered the version to v.4.0.0

I am looking forward to solving this problem.
Thanks for reading my article.

**Comment by fritzschoff** [comment]
created a second entry point, check if that fixes for you. Thanks for the issue!

**Comment by rlagkrdy** [comment]
@fritzschoff 

I uploaded the version and tested it.
It's Perfect!!!

Thank you for solving the problem quickly.
