### ISSUE TITLE
Update angular version to 11 and akita 6

### ISSUE THREAD

**Issue by alexis-mrc** [dappsnation/akita-ng-fire#188]
Hi

I got WARN when building my angular app :

```
npm WARN akita-ng-fire@4.0.1 requires a peer of @angular/common@>=6.0.0 <11 but none is installed. You must install peer dependencies yourself.
npm WARN akita-ng-fire@4.0.1 requires a peer of @angular/core@>=6.0.0 <11 but none is installed. You must install peer dependencies yourself.
npm WARN akita-ng-fire@4.0.1 requires a peer of @angular/router@>=6.0.0 <11 but none is installed. You must install peer dependencies yourself.
```

I am using akita-ng-fire `"akita-ng-fire": "^4.0.1"` with angular 11 and everything seems working great but i am not using everything of the library.
Is enough to update angular version in the package.json ?

I just saw tha akita released a new version (6.0.1) to remove dependency on tslib < 2
```
npm WARN @datorama/akita@5.3.0 requires a peer of tslib@>= 1.7.0 < 2 but none is installed. You must install peer dependencies yourself.
npm WARN @datorama/akita-ng-router-store@5.1.9 requires a peer of tslib@^1.9.0 but none is installed. You must install peer dependencies yourself.
```

I think it would be great to update dependency with akita too.

**Comment by fritzschoff** [comment]
Hey, thanks for letting us know. We will update this lib then to v5.
About the warning that requires the angular libs. What do you mean you are not using anything from the lib?

**Comment by alexis-mrc** [comment]
For the warning, i am using angular >= 11

**Comment by fritzschoff** [comment]
Hey I published version 5 now. Let me know if that fixes it for you. You need akita version 6 now.
