### ISSUE TITLE
Custom Key For Users when Using Auth

### ISSUE THREAD

**Issue by randallmeeker** [dappsnation/akita-ng-fire#193]
I have previously implemented auth where it creates a `profile` in the `users` collection. Is there a way to utilize the users `email` address ad the `idKey` for this instead of the `uid`?

**Comment by fritzschoff** [comment]
Oh sorry missed that one. Will have a look tomorrow CET

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/116221316-cbe47700-a74d-11eb-9a83-a00a701c6ca1.png)
does that do the trick for you?

**Comment by fritzschoff** [comment]
with the current version it isn't possible. You would need to have a flag or a custom function for the signup func. That gets the value from the user object from firebase and sets the wanted value as id. Also you would need to handle this specific case for the auth providers which at that point, would make sense to write your own little services

**Comment by randallmeeker** [comment]
cool, thanks for the info. love this library
