### ISSUE TITLE
syncWithRouter broken after latest fix?

### ISSUE THREAD

**Issue by randallmeeker** [dappsnation/akita-ng-fire#194]
Is sync with router broken?

This change does not seem to match the type

https://github.com/dappsnation/akita-ng-fire/commit/dcf2281bcbee72cbab63cfd70fbbbc21fa349945

```
switchMap(params => this.syncCollection({ params: { params } })),
```

Additional context, here you can see a test setup with the following error

```
ERROR Error: Required parameter orgId from orgs/:orgId/projects doesn't exist in params {"params":{"orgId":"worldwide_productions"}}
```

**Comment by fritzschoff** [comment]
Thanks for letting us know. Will have a look tomorrow CET

**Comment by fritzschoff** [comment]
I don't have this type error. Also it builds fine...

**Comment by fritzschoff** [comment]
Thanks for all the reporting! Hope that should do the trick, will release a new minor version soon
