### ISSUE TITLE
Deleting a collection and recreating it with new data leads to dead entries in the local cache

### ISSUE THREAD

**Issue by Jak3b0** [dappsnation/akita-ng-fire#20]
Hi, I posted this issue on the Akita GitHub but I was told that it might be an issue with this project. (see https://github.com/datorama/akita/issues/296)

## Current behavior

Deleting a collection directly in Firestore and recreating it with new data will leave the local cache with the previous data plus the new items.

## Expected behavior

Only the new items should be in the local cache.

## Minimal reproduction of the problem with instructions

1. Create a collection in Firestore
2. Add some data to it
3. Configure your app to use a `CollectionService` to load the data from firestore
4. Use `persistState` using `localForage` with IndexedDB as the driver
5. Launch the app
6. Close the app (so that a local cache is saved of the data)
7. In Firestore, delete the collection
8. Create a collection with the same name and add some new data to it
9. Launch the app
10. Notice that the old items will still be there and the sync will add the new items leaving the local cache invalid.

**Comment by GrandSchtroumpf** [comment]
Thanks @Jak3b0 for the feedback.

I would recommand to use the [offline option](https://github.com/angular/angularfire2/blob/master/docs/firestore/offline-data.md) from `AngularFirestore` to persist data that are related to Firestore, and use Akita persistState for everything else (UI, form, ...).

We don't have access to firestore history of actions, so it means that I would have either to :
- Query each data in the persistState to be sure they still exist (which increases the amount of read)
- Reset the store before, but then there is no reason to use persistState anymore.

**Comment by Jak3b0** [comment]
Oh yes, it's true that they support it (and probably, more optimized yes 🙂).

I will give this a shot then! Thank you for this!
