### ISSUE TITLE
query selectAll() not triggered on adding new document for subcollections 

### ISSUE THREAD

**Issue by neelz040** [dappsnation/akita-ng-fire#203]
I noticed that for sub collections, when adding a new document it does not trigger the query subscription selectAll(). This results in that the frontend is not updated properly.

In the sub collection service I use:

```
  get path(): string {
    const id = this.routerQuery.getParams().id;
    return `parent/${id}/collection`;
  }

```
In the component I do the following:
```
this.service.sync().subscribe();
this.subCollectionDocs$ = this.query.selectAll();
```
For root collections where the path is simply @StoreConfig({ name: 'collection' }) everything works as expected.

I am using "akita-ng-fire": "^4.3.3" and "firebase": "^8.0.1".

**Comment by fritzschoff** [comment]
Hey, thanks for the report. Will have a look in the upcoming days

**Comment by neelz040** [comment]
So, not sure what happend yesterday but it appears to be working as expected today. 

I will do some further testing and will get back to you.

**Comment by fritzschoff** [comment]
Nice. Let me know the results

**Comment by fritzschoff** [comment]
couldn't find any unusual. Will close this issue
