### ISSUE TITLE
Incorrect OAuth provider when using Apple sign-in

### ISSUE THREAD

**Issue by pallehpetersen** [dappsnation/akita-ng-fire#216]
Hey, I noticed a small bug when attempting to use Apple sign-in using the FireAuthService.

When using the FireAuthService to sign in using OAuth, the Apple AuthProvider is created using "apple" and not "apple.com", so it does not work.

https://github.com/dappsnation/akita-ng-fire/blob/3d019b539147cc1185016dd4d0d8e997273fd8a7/projects/akita-ng-fire/src/lib/auth/auth.service.ts#L53
The line here should be changed to

```typescript
case 'apple': return new firebase.auth.OAuthProvider('apple.com'); 
```

[Firebase documentation](https://firebase.google.com/docs/auth/web/apple#handle_the_sign-in_flow_with_the_firebase_sdk)

**Comment by GrandSchtroumpf** [comment]
@pallehpetersen it has been fixed with version 6.0.5. Thanks for reporting.
