### ISSUE TITLE
Loading state does not work with syncing empty collection

### ISSUE THREAD

**Issue by randallmeeker** [dappsnation/akita-ng-fire#238]
If I'm syncing a collection and it is empty the loading state will not revert to false. 

The loading state does not turn false till we process individual documents. [HERE](https://github.com/dappsnation/akita-ng-fire/blob/0da7d7ecbd209b6501c222993a23bb12dd3768d5/projects/akita-ng-fire/src/lib/utils/sync-from-action.ts#L80)

It would seem to me that we could reset the store [HERE](https://github.com/dappsnation/akita-ng-fire/blob/0da7d7ecbd209b6501c222993a23bb12dd3768d5/projects/akita-ng-fire/src/lib/collection/collection.service.ts#L277) instead of where the results of the sync'd collection is returned.

Thoughts, or am I very wrong here?

**Comment by hakimio** [comment]
Not sure I understand the problem. Do you mean that  [`collectionChanges`](https://github.com/dappsnation/akita-ng-fire/blob/0da7d7ecbd209b6501c222993a23bb12dd3768d5/projects/akita-ng-fire/src/lib/collection/collection.service.ts#L274) never emits anything when collection is empty? Are you setting [`syncOptions.loading` config](https://github.com/dappsnation/akita-ng-fire/blob/0da7d7ecbd209b6501c222993a23bb12dd3768d5/projects/akita-ng-fire/src/lib/collection/collection.service.ts#L266)?

**Comment by randallmeeker** [comment]
I am, but if the returned result of a sync collection is an empty array then loading never goes from TRUE to FALSE. It is set up to only turn the loading state FALSE in `syncStoreFromDocAction` which only processes individual items in the store. If an empty array is returned, then nothing is processed and the loading state stays TRUE.

**Comment by hakimio** [comment]
Can you create a PR with a unit test reproducing the issue?

**Comment by randallmeeker** [comment]
Sure, will see what I can throw together this week. :+1:

**Comment by Benny739** [comment]
Any news here?

**Comment by hakimio** [comment]
@Benny739 feel free to make a PR. Nobody seems to be working on this one.

**Comment by randallmeeker** [comment]
@Benny739 @hakimio Wanted to get this done the 9 to 5 is more like 9 to 9 these days. I'm happy to help, but won't get back to this for another week or so when I hop back on the project I was doing this for. I never really used the loading states in this until I had a brand new project to do so and noticed them broken. I almost 100% I have a valid fix by must moving the setLoadingState higher up in the call action.

**Comment by Benny739** [comment]
Do you have an idea how to solve this? CollectionChanges doesn't emit anything when there is no data. We switched to CollectionData in our app and then we replace all data in the store every time we get new data, but this is not very beautiful.

There is already an open bug in rxfire: https://github.com/FirebaseExtended/rxfire/issues/55

**Comment by randallmeeker** [comment]
Yes, my [original post](https://github.com/dappsnation/akita-ng-fire/issues/238#issue-1125047362) shows where a change could be made. I have been a bit underwater as of late, but should be able to work on this next week. 

The [RxFire](https://github.com/FirebaseExtended/rxfire/issues/55) bug is interesting as I did not encounter than in this, but In my tests I don't know that I'm syncing with a query. I will say if the RxFire bug is legit, solving this problem here will only solve it for syncing w/o a query. RxFire would still have to be fixed for a full solution.

**Comment by luke-rogers** [comment]
Opened #270 which should hopefully fix this issue. 

@Benny739 be great if you could give it a test in your app and feedback.
