### ISSUE TITLE
entity only contains id in update method of CollectionService

### ISSUE THREAD

**Issue by ThierryDD** [dappsnation/akita-ng-fire#24]
The following code fails because wishlist.products in undefined:
```
this.update(wishlist.id.toString(), entity => {
    console.log(wishlist);
    console.log(entity);
    return ({
        products: arrayAdd(entity.products, createProduct())
    })
});
```
On the console we get:
- `wishlist` as the full object: `{ id: "ahsdgfahsdgs", products: [...] }`
- `entity` containing only the `id`: `{ id: "ahsdgfahsdgs" }`

**Comment by GrandSchtroumpf** [comment]
Should be fix on version 1.5.9 with this [bug fix](https://github.com/dappsnation/akita-ng-fire/commit/21fa6d80f91cfa7c1d408263fb136206d012d281#diff-fa4722d31ccd0800aeb5089a9c1c0da3R444)
