### ISSUE TITLE
New feature: beforeCreate hook to alter object before adding it

### ISSUE THREAD

**Issue by ioaNikas** [dappsnation/akita-ng-fire#32]
### I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

I'm working on implementing akita-ng-fire on a pretty big project and some new features would be really nice to help it. One of them is a method that can be use before the `service.add()` to alter an object before adding it.

It should behave pretty much like `onCreate` hook that allows to perfom actions when the document is created. As the document reference doesn't exists in firebase when `onCreate` is called, we need to use something to modify an object in the service before each addition to the collection.

**Comment by dylanwatsonsoftware** [comment]
Is this something different to the akitaPreAddEntity method hook that is already available in Akita? https://netbasal.gitbook.io/akita/general/store-middleware

**Comment by dylanwatsonsoftware** [comment]
Actually, looking at the collection service code, it looks like there is a preFormat method on CollectionService that you could override. The default implementation just takes an entity and returns it.

It _sounds_ like that's what you're looking for?

**Comment by ioaNikas** [comment]
Hello, yes it's different from akitaPreAddEntity which performs modification on the entity before pushing it in the store. Wanted to do the same before pushing it to the database. As I talked with @GrandSchtroumpf , he showed me a CollectionService named `formatToFirestore` that you can override and that behaves the way I wanted.

Thanks for helping with my problem, nice to have people like you around :)
