### ISSUE TITLE
Update with an array of entities

### ISSUE THREAD

**Issue by ioaNikas** [dappsnation/akita-ng-fire#36]
## I'm submitting a...
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

## Current behavior
Native `update` from CollectionService takes either an id, an object, or an array of ids.

## Expected behavior
It would be really convenient if it could take an array of objects, this way we can update each one of them independently within the same `update` call.

**Comment by GrandSchtroumpf** [comment]
Solved
