### ISSUE TITLE
getValue with an array of ids

### ISSUE THREAD

**Issue by ioaNikas** [dappsnation/akita-ng-fire#37]
## I'm submitting a...
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

## Current behavior
We can call `getValue()`  with an id, a query, or empty if we want a snapshot of the whole collection.

## Expected behavior
We should be able to pass an array of ids to retrieve only a part of the collection.

**Comment by GrandSchtroumpf** [comment]
Solved
