### ISSUE TITLE
New feature: Allow a destroyed$ observable to be passed to syncCollection

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [dappsnation/akita-ng-fire#47]
This would simplify the pattern of:
`this.orderService.syncCollection().pipe(takeUntil(destroyed$)).subscribe();`
to something like:
```
this.orderService
      .syncCollectionUntil(this.destroyed$)
```

My initial implementation looks something like:
<pre><code>
  syncCollectionUntil(
    queryOrDestroyed: QueryFn | Observable<boolean>,
    destroyed$?: Observable<boolean>
  ) {
    let queryFn;
    if (isObservable(queryOrDestroyed)) {
      destroyed$ = queryOrDestroyed;
    } else {
      queryFn = queryOrDestroyed;
    }

    return this.syncCollection(queryFn).pipe(takeUntil(destroyed$)).subscribe();
  }
</code></pre>

**Comment by GrandSchtroumpf** [comment]
Hello, thanks for the suggestion. 
Unfortunately this is something that I would like not to do. I tried it with an Observable `path$` parameter and it's a mess to manage, and will be remove in v2.0.0.
Using the default pattern makes things much cleaner and easier to maintain. You can create a utils for that in your app if you want : 
```typescript
function syncCollectionUntil(
  this: CollectionService,
  queryOrDestroyed: QueryFn | Observable,
  destroyed$?: Observable
  ) {
  let queryFn;
  if (isObservable(queryOrDestroyed)) {
    destroyed$ = queryOrDestroyed;
  } else {
    queryFn = queryOrDestroyed;
  }

  return super.syncCollection(queryFn).pipe(takeUntil(destroyed$)).subscribe();
}
```
And in your service: 
```typescript
class MyService extends CollectionService {
  syncCollection = syncCollectionUntil.bind(this) // override the method
  syncCollectionUntil = syncCollectionUntil.bind(this) // new method
}
```

**Comment by dylanwatsonsoftware** [comment]
Fair enough, yeah I can see the optional, parameters thing getting messing quickly!

I found an alternative anyway, possibly a better pattern anyway. Funnily enough, its a Netanel Basal creation as well haha
https://github.com/ngneat/until-destroy

It allows you to just do:
```
@UntilDestroy()
@Component({})
export class OrderComponent {
  ngOnInit() {
     this.orderService.syncCollection().pipe(untilDestroyed(this)).subscribe();
  }
}
```

Thanks!
