### ISSUE TITLE
Missing batch.commit()

### ISSUE THREAD

**Issue by rosostolato** [dappsnation/akita-ng-fire#50]
If I'm not wrong, it seems that it's missing `await batch.commit()` on singup method. That's why it's not creating user profile when user registers with email. 

https://github.com/dappsnation/akita-ng-fire/blob/69ca785a3dcc71b8b4bcc1edc57f75f5f342ac6f/projects/akita-ng-fire/src/lib/auth/auth.service.ts#L128

**Comment by GrandSchtroumpf** [comment]
Thanks for reporting. This is not an issue anymore in versions 2.0.0-alpha.*.
I'll publish a RC version asap that should be stable enough.

**Comment by rosostolato** [comment]
Will you recommend me to use the rc version in production or I need to wait a little bit more?

**Comment by GrandSchtroumpf** [comment]
I think it should be fine. I should not change the code between rc and v2.0.0, mostly the documentation.

**Comment by GrandSchtroumpf** [comment]
Hello, sorry for the delay, the rc1 version is finally out. If you are using the @next version of @angular/fire, you should use rc2 though (`npm install akita-ng-fire@next`).
I'll close this issue, don't hesitate to reopen if you still experience this issue.
