### ISSUE TITLE
Expose EntityStore.removeActive() in CollectionService

### ISSUE THREAD

**Issue by RicardoJBarrios** [dappsnation/akita-ng-fire#51]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

## Current behavior

When a Guard is used to synchronize the active entity, as shown in the documentation, there are situations when you want be to be able to delete the active entity on `CanDeactivate`, for example, but the store's `removeActive`  method is not exposed in `CollectionService`, forcing a dirty trick like this:

```typescript
canDeactivate(): boolean {
  this.service['store'].removeActive(this._id);
  return super.canDeactivate();
}
```

## Expected behavior

To have store's `removeActive` exposed in `CollectionService` or a `syncActive` option to reset or delete the active entity.

**Comment by GrandSchtroumpf** [comment]
why not injecting the store in the guard ?

```typescript
@Injectable({ providedIn: 'root' })
export class MovieListGuard extends CollectionGuard<MovieState> {
  constructor(service: MovieService, private store: MovieStore) {
    super(service);
  }
  canDeactivate(): boolean {
    this.store.removeActive(this._id);
    return super.canDeactivate();
  }
}
```
