### ISSUE TITLE
Runtime error when upgrading to alpha.28

### ISSUE THREAD

**Issue by celsoaguiar** [dappsnation/akita-ng-fire#54]
alpha.28 requires an upgrade of firebase npm, which I did to "7.6.1".
that requires the installation of @firebase/app (0.5.0 or 0.5.4 in my case).
The following error shows in the console and you cannot launch the app:

Uncaught TypeError: app.firestore is not a function at firestore.js:43

**Comment by GrandSchtroumpf** [comment]
Sorry, for the delay.
Is it still an issue with version rc.1 ? Else can I close ?

**Comment by celsoaguiar** [comment]
This seems to be gone, I'm at 7.6.1 and no issues like that on my app
