### ISSUE TITLE
SyncDoc & SyncActive for Collection Queries with 1 return value

### ISSUE THREAD

**Issue by Benny739** [dappsnation/akita-ng-fire#55]
I'm using a url property in my docs for more beautiful routes. So to query my docs I always have to query a collection and set where equal to the url. Would it be possible to also supply a collection query to SyncDoc and SyncActive which always chooses the first element of the query?

**Comment by GrandSchtroumpf** [comment]
Sorry, for the delay...
The syncDoc & syncActive are use `snapshotChanges` method of `AngularFirestore` which doesn't support the QueryFn. I would recommand you to create you own method : 
```typescript
syncFirstDoc(queryFn) {
  return this.syncCollection(ref => queryFn(ref).limit(1))
}
```
