### ISSUE TITLE
Alpha 28 - SyncManyDocs always pulls all Docs from firestore

### ISSUE THREAD

**Issue by Benny739** [dappsnation/akita-ng-fire#56]
As far as I see, SyncManyDocs, will always load all docs from firestore. If I add Ids, it will reload all the documents, what is not very efficient. Just adding the new Ids to the store and keep the old listeners alive would be a more efficient solution in terms of database reads.

**Comment by ex37** [comment]
I am preparing a new `DocumentService`, for the case one need to sync just a document and doesn't need an EntityStore. This will include it's own update, upsert, create, remove methods, as well as ability to update db with `firestore.FieldValue`. Hope that will solve your issue?

**Comment by fritzschoff** [comment]
what is the status of this `DocumentService` ?

**Comment by fritzschoff** [comment]
reopen pls if still ongoing
