### ISSUE TITLE
Best Practice syncing single documents from multiple collections to store

### ISSUE THREAD

**Issue by Benny739** [dappsnation/akita-ng-fire#57]
I have to sync single documents from multiple collections to my store. What is the best practice here? Should I create a feature / Entity Store for each collection and just have one document inside? Or can I create a global store and specify which part of the global state belongs to which doc?

**Comment by GrandSchtroumpf** [comment]
In akita there is no global store. Instead I would recommand to have a store per collection & combine them with the query.
If it happen that you do that a lot I would say that akita-ng-fire (and akita in general) might not be the best solution for you.

**Comment by Benny739** [comment]
Thx for your help, one store per collection is a good solution.
