### ISSUE TITLE
Auth is broken

### ISSUE THREAD

**Issue by celsoaguiar** [dappsnation/akita-ng-fire#58]
You can notice this by launching the sample app included in akita-ng-store and clicking "signin with google". you should get Display Name on the screen, due to "Welcome {{ profile.displayName }}" in template html, but 'profile' has not been populated in the store. check $$stores.auth, 'uid' and 'roles' are populated, 'profile' is undefined.

**Comment by GrandSchtroumpf** [comment]
Hello, sorry for the delay, could you specify the version ? I didn't manage to reproduce with the @latest version.

**Comment by celsoaguiar** [comment]
it was with alpha 28

**Comment by GrandSchtroumpf** [comment]
Is it still the case with verson alpha 29 ?
Did you override the methode "selectProfile" from FireAuthService ?

**Comment by celsoaguiar** [comment]
well, I have not tested with that 29 version. I'll try update. I didn't have to override anything, I just started grabbing the data from another object, in "roles" I think, which is fullfilled by auth.service. It's basically the same data that would be in the "profile" object.

**Comment by celsoaguiar** [comment]
@GrandSchtroumpf, I was able to upgrade to version rc-1 and apparently no issues with auth. I noticed roles is null and profile is available

**Comment by GrandSchtroumpf** [comment]
@celsoaguiar thanks for the feedback.
FYI, if you're working with the next version of @angular/fire there is a bug in version rc1, you'll need to switch to rc2 (akita-ng-fire@next).

**Comment by celsoaguiar** [comment]
thanks, I'm using @ 5.2.1, same as you, haven't upgraded that.
