### ISSUE TITLE
memory leak in syncWithRouter util

### ISSUE THREAD

**Issue by ex37** [dappsnation/akita-ng-fire#59]
https://github.com/dappsnation/akita-ng-fire/blob/v2.0.0/projects/akita-ng-fire/src/lib/utils/sync-with-router.ts#L24
This causes a memory leak, cause it's not refcounted, so the firebase connection will be kept alive, even on unsubscribe. Should be
```
shareReplay({ bufferSize: 1, refCount: true })
```

**Comment by GrandSchtroumpf** [comment]
Can we close ?
