### ISSUE TITLE
Support for Firebase RTDB

### ISSUE THREAD

**Issue by xjuanc** [dappsnation/akita-ng-fire#6]
It'd be great if we could sync stores not only with Firestore but also RTDB

**Comment by xjuanc** [comment]
Any news on this?

**Comment by fritzschoff** [comment]
Yes, I'm thinking about it. You got any ideas how to represent the data in an akita store?

**Comment by xjuanc** [comment]
What I have in mind, which I ain't sure if it's the best way, is to specify the key name used in firebase, the unique id that represents each entity uniqueness in the firebase key and from there on, update everything as necessary.

```
"vehicles": {
   "10": {
      "vehicleId": 10,
      "type": "Motorcycle",
      "latitude": 3.54,
      "longitude": -2.35,
      "origin": "4th Av. New York",
      "driver": {
         "name": "Arnold Schwarzenegger"
         "age": 30
         "license": "C3"
      }
   }
}
```

```
StoreConfig({ firebaseKey: "vehicles", uniqueId: "vehicleId" })
```

The ideal thing here would be keep in sync the vehicles key with the store, therefore every change that occurs is automatically emitted through the query observables.

The tricky part I see is the store naming, since there may be another store called vehicles which is pulled from an http request and possible wanted to keep it that way, for that I can imagine something like another INDEXEDDB(in my case) specially for firebase or, as occurs with formsManager, have a firebase key in the db and everything else under it.

The vehicles store itself i'd keep it as it is right now in Akita

```
firebase: {
   vehicles: {
      entities: {
        "10": { ... },
        "11": { ... }
      },
      ids: [10, 11]
   }
}
```

One more thing: By the time we started using RTDB, the numbers were not parsed into string and therefore we couldn't use 10 as entity key, for a correct use of our current RTDB nodes we would need something like "idHelper: 'N'" in the StoreConfig or something like that which would append the key value, so it would be 10N instead of just N, obviously this is an special usecase.

```
this.firebaseVehicleService.selectAll().subscribe() => { entities: [ {}, {} ] }
this.firebaseVehicleService.selectAll().subscribe() => { entities: [ {}, {} ] }
````

As I've said before I ain't sure how optimal or helpful my post is but this I what I have in mind for it so far. Pretty sure you can come up with better structures and logic than me. 

Notice: I'm not informed in how akita-ng-fire currently works with Firestore, since we don't use Firestore in our company and these are my raw ideas I've had on it without external examples

Greetings.

**Comment by fritzschoff** [comment]
Thanks for the explanation. But one question still remains in my head. Why do you need akita for that? 
`I mean even with firestore, sometimes you do update akita even thou you don't need it. Just listen on these IDs and if the user navigates to the next page you can forget these IDs again. `
But of course, this decision shouldn't be decided by akita ng fire. 
Just to let you know, we where thinking about splitting this library up into several other libs. Like regular akita ng fire operations and one with just useful firebase tools that helps you in your daily angular life.
For RTDB support, I need to dive deep into that and have a look. Maybe I can tackle this issue next week

**Comment by xjuanc** [comment]
Sorry for the delay, been a rough week. 

We don't really need akita nor akita-ng-fire, but we have many apps states handled with Akita and I'd like to continue having it with a kind of similar structure, we also get a huge advantage from cache and the way it handles entities underhood and how it updates it (Queries are also a breeze to work with). 

Right now with the data we get from firebase, we have to handle OnAdd, OnChanges, OnRemove, and inside OnChanges we have to manually validate each property one by one because the replace function is kind of heavy for the amount of data we are handling per second (And for requirements we can't cap this down) and the update function doens't work properly because of the way we handle the data in certain nodes (for example removing properties from root or deep objects).

Taking this into account and that we have several modules with kind of similar realtime requirements, we really think we could take a huge benefit out of a tool that keeps an store in sync with an specific node by itself which is what we found akita-ng-fire does but with Firestore.

As I've said at the beginning we have all theses products working properly and we dont NEED this right now, but I'm pretty sure it'd be a great plus both for me and other people aswell.

Thanks in advance and sorry for the long response.

**Comment by fritzschoff** [comment]
okay, I would love to support RTDB. I will have a look into it tomorrow. I never worked with RTDB so I might have some question for you on the way.

**Comment by fritzschoff** [comment]
ref https://github.com/dappsnation/akita-ng-fire/tree/issue-6

**Comment by fritzschoff** [comment]
I finally got the time to have a look into rtdb. Maybe you can try it out and tell me what do you think about it. But don't expect too much since it is a very minimum version which doesn't support dynamic node names for instance.
`npm i akita-ng-fire@4.1.0-beta.1
`

**Comment by fritzschoff** [comment]
closing it for now
