### ISSUE TITLE
CollectionGuard throws error with RouterStore in canDeactivate

### ISSUE THREAD

**Issue by Benny739** [dappsnation/akita-ng-fire#62]
Version: 2.0.0-alpha.29

When working with the RouterQuery, collection guard throws an error, when route gets deactivated:

> Error: You should provide either an "id" OR a "path".
    at getIdAndPath (akita-ng-fire.js:45)

 ```
  protected sync(next: ActivatedRouteSnapshot) {

    const schoolId = this.maQuery.getSchoolId();
    const uid = this.authQuery.getUID();

    return this.routerQuery.selectParams<string>(['courseId', 'chapterId']).pipe(
      switchMap(([courseId, chapterId]) =>
        this.service.syncDoc({ id: chapterId }, { params: { schoolId, courseId, uid } })),
    );

  }
```

**Comment by GrandSchtroumpf** [comment]
Hello, this happens when you don't provide a string value to you id. If the chapterId is undefined or null for example. You can easily try this hypothesis by doing : 
```typescript
pipe(
  filter(([courseId, chapterId] => !!courseId && !!chapterId),
  switchMap(([courseId, chapterId]) => ... )
)
```

**Comment by Benny739** [comment]
This makes sense.
