### ISSUE TITLE
syncCollection can show deleted docs

### ISSUE THREAD

**Issue by Benny739** [dappsnation/akita-ng-fire#64]
It can happen that syncCollection shows deleted Docs. If we delete a doc on a different device and the store still has this in memory, the deleted data is not removed from the store.

I suggest to add a reset option to the sync options and if set to true, the store gets resetted before the first sync happens.

If you're willing to accept a PR I would implement this in the 2.0.0 branch.

**Comment by GrandSchtroumpf** [comment]
Hello,
I don't understand how you ends up having deleted docs in the store while syncing. The service should listen on the "remove" event and impact the store in consequence.
I'm ok with the reset option, but not to set it at false, else you loose all the interest of `awaitAsync` in the guard.

**Comment by Benny739** [comment]
Hi,
this can happen when you're using the app on multiple devices at the same time or you have multiple users editing the same data, but not everyone is in sync.
Imagine an app, with 2 collections books and movies. On the first device you open books and then navigate to movies. Then you leave the browser open and switch to your mobile and delete a book there. The Books collection is still in the store on device 1 and when I navigate back to the books collection the "remove" event hasn't happend, because it was not in sync while the deletion happend. The sync then just receives "added" events and the deleted book is still in the store.

I think the best solution to this would be to use set on the first sync, this way you keep things like your active id, but I can't see an elegant way for this atm.
I would call resetStore at the same time when you set the loading state, I don't think this will affect the guard in any way.

**Comment by GrandSchtroumpf** [comment]
fixed with #70. Thanks for the PR.

**Comment by Benny739** [comment]
You're welcome. Any timeline for the next release?

**Comment by GrandSchtroumpf** [comment]
I am waiting for another PR and I release RC. I hope today or tomorrow.
