### ISSUE TITLE
Unable to set provider options

### ISSUE THREAD

**Issue by DavMig** [dappsnation/akita-ng-fire#77]
Hello,

RIght now, it seems to be impossible to get the provider object and set custom parameters
For example, I'll would like to use one tenant only for Azure AD authentication, it is possible to set such parameter in Firebase.

```javascript
provider.setCustomParameters({
  // Optional "tenant" parameter in case you are using an Azure AD tenant.
  // eg. '8eaef023-2b34-4da1-9baa-8bc8c9d6a490' or 'contoso.onmicrosoft.com'
  // or "common" for tenant-independent tokens.
  // The default value is "common".
  tenant: 'TENANT_ID'
});
```
src : https://firebase.google.com/docs/auth/web/microsoft-oauth

Is this something that will be planned for future releases ?

Thanks.

**Comment by GrandSchtroumpf** [comment]
Hello,
We could include it in a future release yes. There is already a [method to create the provider](https://github.com/dappsnation/akita-ng-fire/blob/v2.0.0/projects/akita-ng-fire/src/lib/auth/auth.service.ts#L45). We should just accept the provider as [parameter of the signin method](https://github.com/dappsnation/akita-ng-fire/blob/v2.0.0/projects/akita-ng-fire/src/lib/auth/auth.service.ts#L251) and check if `typeof provider === 'object'` I guess.
Like that you could do : 
```typescript
const provider = getAuthProvider('microsoft');
provider.setCustomParameters({ ... });
await service.signin(provider);
```
Would it solve your issue ?

**Comment by DavMig** [comment]
Yes that would solve this issue , right now  I'm overloading  the `signin` method which is not elegant (but works).

Thank you.

**Comment by GrandSchtroumpf** [comment]
It should be part of version 2.0.0-rc.3 now (tag `next`)
