### ISSUE TITLE
isNewUser property is unreliable when creating user in Firebase Console

### ISSUE THREAD

**Issue by DavMig** [dappsnation/akita-ng-fire#79]
Hello, 

When you create a brand new user in the firebase console (native login/password auth from firebase) and then you signin with that user, the profile is never created on the firebase collection.

The reason is that the property isNewUser is set to false even if the user has never logged in.
As a result the check [here](https://github.com/dappsnation/akita-ng-fire/blob/v2.0.0/projects/akita-ng-fire/src/lib/auth/auth.service.ts#L272) does not pass and profile is never created on firebase.

So far I've seen this behaviour only  for the  native firebase auth (Microsoft auth just works fine).

I've bypassed this by making a call directly to firebase to check if profile document exists.
A solution that may work is to let the developer define a callback function to check if the profile should be created.

Thanks.

**Comment by Maxstgt** [comment]
Hello,
if I'm not mistaken but `isNewUser` is going to be set by angular/fire, so this seems to be an angular/fire issue?

**Comment by fritzschoff** [comment]
Hey, checkout v2.0.3, you should have more context now!
