### ISSUE TITLE
Add Transaction hooks for side effect on database

### ISSUE THREAD

**Issue by GrandSchtroumpf** [dappsnation/akita-ng-fire#8]
Use case : 
When adding a stakeholder to a movie, also add the movieId to the stakeholder.

How to : 
- [ ] Update should always be in a transaction
- [ ] Create hooks on CollectionService to listen on specific actions

**Comment by loicmarie** [comment]
:+1: I would like to have this feature too. AkitaNgFire is a great idea, but I don't think it is usable in prod without transactions. Without it, it's hard to make basic atomic entity-relationships operations. As stated above, cascading udpates are important, but I will add as well :

- Cascading deletions (user is deleted, so comments of user are deleted, tags of comment are deleted, etc)
- Cascading creations

I think this feature (transactions) should be the most important, as I don't think anyone with a decent data modeling will be able to use it.

I saw in the doc that I "shouldn't update the store yourself", but that's not possible to keep this philosophy when it comes to add transactions. Akita users need to make **database operations atomic**, and this logic depend on how the developper has modeled the database (is the collection A associated with B via foreign key ? Embedded document ? Group document ? Middle collection ?). The developer has to handle it himself.

What about being able to override the three CRUD methods ? Or to have a transaction instance parameter, that is auto-committed at the end of the function ?

**Comment by GrandSchtroumpf** [comment]
I agree this is a **must have**. I'll work on that asap. I think hooks like that should be enough : 
- `onCreate(transaction, entity)`
- `onUpdate(transaction, entity)`
- `onDelete(transaction, entity)`

The best whould be to have a **simple way** to chain services hooks with a single transaction. But I'll need to update deeply the service to support that. 
The doc says not to update the store yourself because this is the role of Firebase. The state should be in sync with Firebase, so if you update it yourself, the end user will not see the "real" state of the app.
Also, I wouldn't recommand to override the CRUD methods as you might have some weird side effects with future utils functions.
