### ISSUE TITLE
Dynamic store question

### ISSUE THREAD

**Issue by architechcro** [dappsnation/akita-ng-fire#99]
Hi,
I'm trying out akita-ng-fire and have a question regarding dynamic store and I'm not sure it can be used in my use case.
Use case involves using one store and two services - one http and one Firebase. If the entity is not available from the Firestore it will be fetched from http service. Http service fetches "master" data ( remote service ) and updates Firestore ( app database ). 
It is basically syncing http service with Firestore.
Can this syncing be achieved through sharing of the store ?

**Comment by GrandSchtroumpf** [comment]
Hello,
I think there is a design issue here. It's not the job of the frontend to sync external data with the database. I would recommand seting up a webhook from your "master" data to Firestore. Or a simple cron that fetch the data every X time.
In any case this should be a server to server relationship.
I'll close but don't hesitate to reopen if I didn't answer your question.
